import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"/> */}
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet" />
      {/* <link rel="stylesheet" href="pe-icon-set-weather\css\pe-icon-set-weather.css"/> */}


{/* <link rel="stylesheet" href="path/to/pe-icon-set-weather/css/helper.css"/> */}
      </head>
      <body suppressHydrationWarning={true} className={inter.className}>{children}
    
      </body>
    </html>
  )
}
